module.exports = {
    user: 'user',
    category: 'category',
    state: 'state',
    country: 'country',
    shape: 'shape',
    inventory_location: 'inventory_location',
    address: 'address',
    company: 'company',
    size: 'size',
    item: 'item',
    item_info: 'item_info',
    item_image: 'item_image',
    related_item: 'related_item',
    customer: 'customer',
    billing: 'billing',
    cart: 'cart',
    repair: 'repair',
    charges: 'charges',
    spare_parts: 'spare_parts'
  };